repositories:
  - name: "llmnpc"
    path: "/home/m/Junk/llmnpc"
    description: "chroma"
    group: "Junk"
  - name: "dotfiles"
    path: "/home/m/.dotfiles"
    description: "Git frontend in Go"
    group: "Personal"
  - name: "chroma"
    path: "/home/m/Junk/chroma"
    description: "chroma"
    group: "Junk"
  - name: "glitch"
    path: "/home/m/Junk/glitch"
    description: "glitch"
    group: "Junk"
  - name: "qwe-editor"
    path: "/home/m/Junk/qwe-editor"
    description: "qwe-editor"
    group: "Junk"
  - name: "parakeet"
    path: "/home/m/Junk/parakeet"
    description: "parakeet"
    group: "Junk"
  - name: "bbgit"
    path: "/home/m/Projects/bbgit"
    description: "Git frontend in Go"
    group: "Projects"
  - name: "beyond-return"
    path: "/home/m/Projects/beyond-return"
    description: "discovered from ~/Projects"
    group: "Projects"
  - name: "fpsgame"
    path: "/home/m/Projects/fpsgame"
    description: "discovered from ~/Projects"
    group: "Projects"
  - name: "stalag"
    path: "/home/m/Projects/stalag"
    description: "discovered from ~/Projects"
    group: "Projects"
